import { useState } from "react"
import { Button } from "@/components/ui/button"
import { METHOD_SHEETS } from "../data/matrices"
import type { Locale } from "@/features/chemistry/types/models"

type Props = { locale: Locale }

export function MethodCard({ locale }: Props) {
  const [idx, setIdx] = useState(0)
  const ms = METHOD_SHEETS[idx]

  return (
    <div className="space-y-4">
      <p className="text-xs text-muted-foreground">
        {locale === "es"
          ? "Fichas operativas: reactivos, condiciones, cálculos clave, riesgos analíticos y checklist de ejecución."
          : "Operational sheets: reagents, conditions, key calculations, analytical risks and execution checklist."}
      </p>

      <div className="flex gap-1.5">
        {METHOD_SHEETS.map((m, i) => (
          <Button key={i} size="sm" variant={i === idx ? "default" : "outline"} onClick={() => setIdx(i)}>
            {m.title[locale]}
          </Button>
        ))}
      </div>

      <div className="rounded border-2 border-primary/30 bg-card p-4 space-y-3 print:border-black">
        <div className="text-sm font-bold text-center border-b border-border pb-2">{ms.title[locale]}</div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <div className="text-[10px] font-medium text-muted-foreground mb-1">{locale === "es" ? "REACTIVOS" : "REAGENTS"}</div>
            {ms.reagents.map((r) => (
              <div key={r.name} className="text-xs flex justify-between">
                <span>{r.name}</span>
                <span className="font-mono text-muted-foreground">{r.amount}</span>
              </div>
            ))}
          </div>
          <div>
            <div className="text-[10px] font-medium text-muted-foreground mb-1">{locale === "es" ? "CONDICIONES" : "CONDITIONS"}</div>
            <div className="text-xs text-foreground">{ms.conditions[locale]}</div>
          </div>
        </div>

        <div>
          <div className="text-[10px] font-medium text-muted-foreground mb-1">{locale === "es" ? "CÁLCULOS CLAVE" : "KEY CALCULATIONS"}</div>
          {ms.keyCalculations.map((c, i) => (
            <div key={i} className="text-xs font-mono bg-muted/20 rounded px-2 py-0.5 mb-0.5">{c}</div>
          ))}
        </div>

        <div>
          <div className="text-[10px] font-medium text-muted-foreground mb-1">{locale === "es" ? "RIESGOS ANALÍTICOS" : "ANALYTICAL RISKS"}</div>
          {ms.risks.map((r, i) => (
            <div key={i} className="text-xs text-amber-600 dark:text-amber-400">⚠ {r[locale]}</div>
          ))}
        </div>

        <div>
          <div className="text-[10px] font-medium text-muted-foreground mb-1">{locale === "es" ? "CHECKLIST" : "CHECKLIST"}</div>
          {ms.checklist.map((c, i) => (
            <div key={i} className="text-xs flex items-center gap-1.5">
              <input type="checkbox" className="h-3 w-3" />
              <span>{c[locale]}</span>
            </div>
          ))}
        </div>

        <div className="text-[8px] text-muted-foreground text-right pt-2 border-t border-border">
          {locale === "es" ? "Generado por Acid-Base Dynamics" : "Generated by Acid-Base Dynamics"} — {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  )
}
